#!/usr/bin/env bash
# Install (or remove) the two launchd agents that keep the display alive on macOS:
#
#   <prefix>.training-display         render.py, every 15 min 06:00–22:45, plus RunAtLoad
#   <prefix>.training-display-server  server.py, KeepAlive (restarts if it dies, starts at login)
#
# Nothing personal is baked into the repo: label prefix, python, log dir and the
# optional failure-wrapper are arguments. Plists land in ~/Library/LaunchAgents.
#
# Usage
#   scripts/install_launchd.sh [--prefix com.example] [--python PATH] [--guard PATH] [--uninstall]
#
#   --prefix   label prefix (default: com.$USER)
#   --python   interpreter (default: <repo>/venv/bin/python, else ~/.local/state/training-display/venv/bin/python)
#   --guard    a wrapper script run as `guard <name> <cmd...>` around render.py so a
#              failed render is loud (notification / heartbeat); omitted = run directly
#   --uninstall  bootout + delete both plists
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
PREFIX="com.${USER}"
PYTHON=""
GUARD=""
UNINSTALL=0
while [ $# -gt 0 ]; do
  case "$1" in
    --prefix) PREFIX="$2"; shift 2 ;;
    --python) PYTHON="$2"; shift 2 ;;
    --guard) GUARD="$2"; shift 2 ;;
    --uninstall) UNINSTALL=1; shift ;;
    *) echo "unknown arg: $1" >&2; exit 64 ;;
  esac
done
if [ -z "$PYTHON" ]; then
  for c in "$REPO/venv/bin/python" "$HOME/.local/state/training-display/venv/bin/python"; do
    [ -x "$c" ] && PYTHON="$c" && break
  done
fi
[ -n "$PYTHON" ] || { echo "no venv found; pass --python" >&2; exit 1; }

AGENTS="$HOME/Library/LaunchAgents"
LOGS="$HOME/Library/Logs"
RENDER_LABEL="$PREFIX.training-display"
SERVER_LABEL="$PREFIX.training-display-server"
UID_="$(id -u)"

bootout() {
  launchctl bootout "gui/$UID_/$1" 2>/dev/null || true
  # bootout returns before a running job has exited; bootstrapping over it fails with "5: Input/output error"
  for _ in 1 2 3 4 5 6 7 8 9 10; do
    launchctl print "gui/$UID_/$1" >/dev/null 2>&1 || return 0
    sleep 0.5
  done
}

if [ "$UNINSTALL" = 1 ]; then
  bootout "$RENDER_LABEL"; bootout "$SERVER_LABEL"
  rm -f "$AGENTS/$RENDER_LABEL.plist" "$AGENTS/$SERVER_LABEL.plist"
  echo "removed $RENDER_LABEL and $SERVER_LABEL"
  exit 0
fi

mkdir -p "$AGENTS" "$LOGS"

# --- render job: every 15 min 06:00–22:45, replayed on load (a cold boot does not replay missed fires).
# Cheap: one calendar call, ~2 s. A render that changes nothing writes the same PNG bytes, so
# the panel (which redraws only on a hash change) stays still; it just picks up edits sooner.
{
cat <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>$RENDER_LABEL</string>
	<!-- Generated by scripts/install_launchd.sh in the training-display repo.
	     Renders today.png every 15 minutes; the server just serves whatever is there.
	     When the calendar is unreachable render.py draws a stale-stamped frame
	     (the last good one, or today with the rows marked offline), so a failure
	     here is never a blank wall — but it still exits non-zero so the wrapper
	     (if any) can shout. -->
	<key>ProgramArguments</key>
	<array>
EOF
if [ -n "$GUARD" ]; then
  printf '\t\t<string>/bin/sh</string>\n\t\t<string>%s</string>\n\t\t<string>training-display</string>\n' "$GUARD"
fi
cat <<EOF
		<string>$PYTHON</string>
		<string>$REPO/render.py</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
	<key>StandardOutPath</key>
	<string>$LOGS/training-display.log</string>
	<key>StandardErrorPath</key>
	<string>$LOGS/training-display.log</string>
	<key>StartCalendarInterval</key>
	<array>
EOF
for h in $(seq 6 22); do
  for m in 0 15 30 45; do
    printf '\t\t<dict><key>Hour</key><integer>%d</integer><key>Minute</key><integer>%d</integer></dict>\n' "$h" "$m"
  done
done
cat <<EOF
	</array>
	<key>WorkingDirectory</key>
	<string>$REPO</string>
</dict>
</plist>
EOF
} > "$AGENTS/$RENDER_LABEL.plist"

# --- server: always on
cat > "$AGENTS/$SERVER_LABEL.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>$SERVER_LABEL</string>
	<!-- Generated by scripts/install_launchd.sh in the training-display repo.
	     LAN-only HTTP server for the frame and the TRMNL device protocol. -->
	<key>ProgramArguments</key>
	<array>
		<string>$PYTHON</string>
		<string>$REPO/server.py</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
	<key>KeepAlive</key>
	<true/>
	<key>ThrottleInterval</key>
	<integer>10</integer>
	<key>StandardOutPath</key>
	<string>$LOGS/training-display-server.log</string>
	<key>StandardErrorPath</key>
	<string>$LOGS/training-display-server.log</string>
	<key>WorkingDirectory</key>
	<string>$REPO</string>
</dict>
</plist>
EOF

for label in "$RENDER_LABEL" "$SERVER_LABEL"; do
  plutil -lint -s "$AGENTS/$label.plist"
  bootout "$label"
  launchctl bootstrap "gui/$UID_" "$AGENTS/$label.plist"
  echo "loaded $label"
done
echo "logs: $LOGS/training-display.log, $LOGS/training-display-server.log"
